name: 'Setup Minikube Kubernetes Cluster'
description: 'This action sets up a single node Kubernetes Cluster in your environment using Minikube'
author: 'Marc Nuri'
branding:
  icon: anchor
  color: blue
inputs:
  minikube version:
    description: 'Version of Minikube to deploy'
    required: true
  kubernetes version:
    description: 'Version of Kubernetes to deploy'
    required: true
  github token:
    description: 'GITHUB_TOKEN to be able to perform requests to GH REST API (with no limit)'
runs:
  using: 'node12'
  main: 'src/index.js'
